{
    avatar_url: "https://avatars1.githubusercontent.com/u/13780134?v=4",
    bio: "A Full Stack Web Developer By Profession",
    blog: "",
    company: null,
    created_at: "2015-08-13T10:16:27Z",
    email: "sahilgoyal.190@gmail.com",
    events_url: "https://api.github.com/users/Sahilgoyal190/events{/privacy}",
    followers: 3,
    followers_url: "https://api.github.com/users/Sahilgoyal190/followers",
    following: 1,
    following_url: "https://api.github.com/users/Sahilgoyal190/following{/other_user}",
    gists_url: "https://api.github.com/users/Sahilgoyal190/gists{/gist_id}",
    gravatar_id: "",
    hireable: null,
    html_url: "https://github.com/Sahilgoyal190",
    id: 13780134,
    location: "India",
    login: "Sahilgoyal190",
    name: "Sahil Goyal",
    organizations_url: "https://api.github.com/users/Sahilgoyal190/orgs",
    public_gists: 0,
    public_repos: 11,
    received_events_url: "https://api.github.com/users/Sahilgoyal190/received_events",
    repos_url: "https://api.github.com/users/Sahilgoyal190/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/Sahilgoyal190/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Sahilgoyal190/subscriptions",
    type: "User",
    updated_at: "2018-01-29T20:52:09Z",
    url: "https://api.github.com/users/Sahilgoyal190"
}